local English = {
	v_loc = 9.01,
	otdt_msg = "错误: 该版本翻译已过时",
	[1] = {
		[1] = {"Legitbot",},
		[2] = {"Ragebot",},
		[3] = {"Visuals",},
		[4] = {"Misc",},
		[5] = {"Settings",},
	},
	[2] = {
		[1] = {"Master Switch",},
		[2] = {"Master Switch",},
		[3] = {"Master Switch",},
		[4] = {"Master Switch",},
	},
	[3] = {
		[1] = {"Aimbot",},
		[2] = {"Triggerbot",},
		[3] = {"Weapon",},
		[4] = {"Other",},
		[5] = {"Semirage",},
		[6] = {"Aimbot",},
		[7] = {"Accuracy",},
		[8] = {"Hitscan",},
		[9] = {"Anti-Aim",},
		[10] = {"Overlay",},
		[11] = {"Local",},
		[12] = {"World",},
		[13] = {"Chams",},
		[14] = {"Skins",},
		[15] = {"Other",},
		[16] = {"General",},
		[17] = {"Movement",},
		[18] = {"Enhancement",},
		[19] = {"Configurations",},
		[20] = {"Lua Scripts",},
		[21] = {"Theme",},
		[22] = {"Advanced",},
	},
	[4] = {
		[1] = {"Toggle",},
		[2] = {"Weapon",},
		[3] = {"Hitbox Selection",{"Order of hitboxes the aimbot will choose.",},},
		[4] = {"Toggle",},
		[5] = {"Weapon",},
		[6] = {"Hitbox Scan",{"Trigger on selected hitboxes.",},},
		[7] = {"Aiming",},
		[8] = {"Visibility",},
		[9] = {"Accuracy",},
		[10] = {"Target",},
		[11] = {"Movement",},
		[12] = {"Extra",},
		[13] = {"Aimbot",},
		[14] = {"Position Adjustment",},
		[15] = {"Anti-Aim",},
		[16] = {"Toggle",},
		[17] = {"Automation",},
		[18] = {"Target",},
		[19] = {"Extra",},
		[20] = {"Weapon",},
		[21] = {"Position Adjustment",},
		[22] = {"Weapon Movement",},
		[23] = {"Movement",{"Amount of points the aimbot will scan for.",},},
		[24] = {"Hitbox Points",},
		[25] = {"Advanced",},
		[26] = {"Mode",},
		[27] = {"Base Direction",},
		[28] = {"Left Direction",},
		[29] = {"Right Direction",},
		[30] = {"Extra",},
		[31] = {"Condition",},
		[32] = {"Advanced",},
		[33] = {"Friendly",},
		[34] = {"Enemy",},
		[35] = {"Weapon",},
		[36] = {"Camera",},
		[37] = {"Helper",},
		[38] = {"Extra",},
		[39] = {"Materials",},
		[40] = {"Nade",},
		[41] = {"Selection",},
		[42] = {"Model",},
		[43] = {"Attachments",},
		[44] = {"Ragdoll",},
		[45] = {"Backtrack",},
		[46] = {"Model",},
		[47] = {"Attachments",},
		[48] = {"Ragdoll",},
		[49] = {"Model",},
		[50] = {"Viewmodel Weapon",},
		[51] = {"Viewmodel Arms",},
		[52] = {"Attachments",},
		[53] = {"Ghost",},
		[54] = {"Weapon",},
		[55] = {"Nades",},
		[56] = {"Change visual items",},
		[57] = {"Extra",},
		[58] = {"Effects",},
		[59] = {"Performance",},
		[60] = {"Restrictions",},
		[61] = {"Bypass",},
		[62] = {"Server",},
		[63] = {"Extra",},
		[64] = {"logs",},
		[65] = {"Jump",},
		[66] = {"Other",},
		[67] = {"Autothrow",},
		[68] = {"Strafe",},
		[69] = {"Fakelag",},
		[70] = {"Fakelatency",},
		[71] = {"Appearance",},
		[72] = {"Manage configurations",},
		[73] = {"Manage scripts",},
		[74] = {"Window Header",},
		[75] = {"Navigation",},
		[76] = {"Window Footer",},
		[77] = {"UI",},
		[78] = {"Tab List",},
		[79] = {"Manage advanced settings",},
	},
	[5] = {
		[1] = {"Enable",{"Enables legit aimbot.",},},
		[2] = {"Aim Key",{"Set the aimbot on key.",},},
		[3] = {"Toggle Key",{"Set the toggle key to enable/disable aimbot.",},},
		[4] = {"Auto Fire",{"Fires without pressing any key.",},},
		[5] = {"Fire On Press",{"Fires when pressing the aimbot key.",},},
		[6] = {"Auto Pistol Interval",{"Interval between shots for automatic mode.",},},
		[7] = {"Enable",{"Enables triggerbot.",},},
		[8] = {"Trigger Key",{"Activate triggerbot on key press.",},},
		[9] = {"Auto Fire",{"Let triggerbot fire without pressing any key.",},},
		[10] = {"Walk Speed Customization",{"Enable walk speed modifications.",},},
		[11] = {"Walk Speed",{"Modify walk speed with this amount.",},},
		[12] = {"Quick Stop",{"Makes you stop faster by counter strafing.",},},
		[13] = {"Backtrack Time",{"How many positions in the past are allowed.",},},
		[14] = {"Knife Triggerbot",{"Enable knife triggerbot.",},},
		[15] = {"Silent Aimbot",{"Autoaim when in Low FOV range.",},},
		[16] = {"Auto Stop",{"Stop when aimbot fires to lower inaccuracy.",},},
		[17] = {"Backtracking",{"Aim at enemy history positions.",},},
		[18] = {"Resolver",{"Improve accuracy when shooting at enemy anti-aim.",},},
		[19] = {"Type",{"Maximum affects visible animation.",{[1] = "Off",[2] = "Minimum",[3] = "Maximum",},},},
		[20] = {"Direction",{"Choose mode for selecting direction.",{[1] = "Auto",[2] = "Manual",},},},
		[21] = {"Left Side",},
		[22] = {"Right Side",},
		[23] = {"On Enemy Aiming",{"Activate anti-aim only when enemy is aiming at you.",},},
		[24] = {"Disable On Knife",{"Disable anti-aim when holding knife.",},},
		[25] = {"Disable On Grenade",{"Disable anti-aim when holding a grenade.",},},
		[26] = {"Enable",{"Enables rage aimbot.",},},
		[27] = {"Auto Pistol",{"Makes pistol fire like an automatic weapon.",},},
		[28] = {"Auto Revolver",{"Auto cocks the revolver for quicker fire.",},},
		[29] = {"Auto Scope",{"Scopes with sniper automatically when firing.",{[1] = "Off",[2] = "On - Auto Unzoom",[3] = "On - No Unzoom",},},},
		[30] = {"FOV",{"Maximum field of view the aimbot will target within.",},},
		[31] = {"Aim Lock",{"Increase priority of latest target.",},},
		[32] = {"Silent Aim",{"Supress view movement when aimbotting.",},},
		[33] = {"Knifebot",{"Automatically knife when your target is in range.",{[1] = "Off",[2] = "Default Knifebot",[3] = "Only Backstab",[4] = "Quick Stab",},},},
		[34] = {"Backtracking",{"Aim at enemy history positions.",},},
		[35] = {"Resolver",{"Improve accuracy when shooting at enemy anti-aim.",{[1] = "Off",[2] = "Default",},},},
		[36] = {"Slow Walk Key",{"Slow down player movement while holding this key.",},},
		[37] = {"Slow Walk Speed",{"Scale movement speed by this value.",},},
		[38] = {"Quick Stop",{"Makes you stop faster by counter strafing.",},},
		[39] = {"Max Processing Time",{"Lower this value to maintain better FPS.",},},
		[40] = {"Precise Hitscan",{"Enable additional checks when selecting hit points.",},},
		[41] = {"Predictive",{"Wait for higher damage spot when peeking.",},},
		[42] = {"Fake Duck",{"Allows you to shoot higher while crouching.",},},
		[43] = {"Fake Duck Style",{[2] = {[1] = "Duck",[2] = "Unduck",},},},
		[44] = {"Static Legs",{"Makes your legs static when slow walking.",},},
		[45] = {"Disable Conditions",},
		[46] = {"Shift On Shot",{"Prevent your on shot model from getting hit.",},},
		[47] = {"Anti-Align Type",{[2] = {[1] = "Lowerbody",[2] = "Micromovement",},},},
		[48] = {"Auto Direction",{"Set anti-aim based on enemy position.",},},
		[49] = {"Auto Direction Priority",{[2] = {[1] = "FOV Based",[2] = "Distance Based",},},},
		[50] = {"Anti-Resolver",{"Makes continous shots harder to hit.",},},
		[51] = {"Pitch Angle",{[2] = {[1] = "Off",[2] = "89°",[3] = "180°(Untrusted)",},},},
		[52] = {"Fake Expose Toggle",{"Flick fake head on edge when enabled.",},},
		[53] = {"Fake Expose Type",{"Method of fake expose",{[1] = "1s",[2] = "1.5s",},},},
		[54] = {"Box",{"Draw 2D box around entity.",{[1] = "Off",[2] = "Outlined",[3] = "Normal",},},},
		[55] = {"Box Precision",{"Match 2D box around entity.",},},
		[56] = {"Name",{"Draw entity name.",},},
		[57] = {"Skeleton",{"Draw player skeleton.",},},
		[58] = {"Health",{"Configure health options.",},},
		[59] = {"Armor",{"Indicate helmet and kevlar.",},},
		[60] = {"Weapon",{"Draw weapon of player.",{[1] = "Off",[2] = "Icon",[3] = "Name",},},},
		[61] = {"Weapon Filter",{[2] = {[1] = "Active",[2] = "Active + Nades",[3] = "All",},},},
		[62] = {"Ammo",{"Amount of ammo left in weapon.",},},
		[63] = {"Flags",{"Show player activity.",},},
		[64] = {"Money",{"Draw amount of money player has.",},},
		[65] = {"Barrel",{"Draw lines where players is looking.",},},
		[66] = {"Dormant",{"Show dormant players.",},},
		[67] = {"Box",{"Draw 2D box around entity.",{[1] = "Off",[2] = "Outlined",[3] = "Normal",},},},
		[68] = {"Box Precision",{"Match 2D box around entity.",},},
		[69] = {"Name",{"Draw entity name.",},},
		[70] = {"Skeleton",{"Draw player skeleton.",},},
		[71] = {"Health",{"Configure health options.",},},
		[72] = {"Armor",{"Indicate helmet and kevlar.",},},
		[73] = {"Weapon",{"Draw weapon of player.",{[1] = "Off",[2] = "Icon",[3] = "Name",},},},
		[74] = {"Weapon Filter",{[2] = {[1] = "Active",[2] = "Active + Nades",[3] = "All",},},},
		[75] = {"Ammo",{"Amount of ammo left in weapon.",},},
		[76] = {"Flags",{"Show player activity.",},},
		[77] = {"Money",{"Draw amount of money player has.",},},
		[78] = {"Barrel",{"Draw lines where players is looking.",},},
		[79] = {"Dormant",{"Show dormant players.",},},
		[80] = {"Box",{"Draw 2D box around entity.",{[1] = "Off",[2] = "Outlined",[3] = "Normal",},},},
		[81] = {"Name",{"Draw entity name.",{[1] = "Off",[2] = "Icon",[3] = "Name",},},},
		[82] = {"Ammo",{"Amount of ammo left in weapon.",},},
		[83] = {"Nades",{"Draw thrown nades.",},},
		[84] = {"C4 Timer",{"Display time till C4 explosion.",},},
		[85] = {"Danger Zone Items",{"Various items from danger zone.",},},
		[86] = {"Danger Zone Turret",{"Turret from danger zone.",},},
		[87] = {"Third Person Enable",{"Toggle third person view with this key.",},},
		[88] = {"Third Person Distance",{"Distance of the camera.",},},
		[89] = {"View FOV",{"Oveeride the game filed of view.",},},
		[90] = {"Viewmodel FOV",{"Override the model field of view.",},},
		[91] = {"Smooth Ghost Model",{"Match fake ghost model position with real.",},},
		[92] = {"Wallbang Info",{"Show penetrable space on walls.",},},
		[93] = {"Out Of View",{"Display out of view enemies indicator.",{[1] = "Off",[2] = "Arrow",[3] = "Arrow + Info",},},},
		[94] = {"Out Of View Scale",{"Scale the positioning of indicators from screen center.",},},
		[95] = {"Hit Effects",{"Effects when hitting an enemy.",},},
		[96] = {"Damage Indicator",},
		[97] = {"Bullet Tracers Mode",{"Visualize bullet pahts.",{[1] = "Off",[2] = "Latest",[3] = "All",},},},
		[98]  = {"Bullet Tracers Filter",},
		[99]  = {"Sounds",{"Display audible sounds on screen.",},},
		[100] = {"Walls Color",},
		[101] = {"Static Props Color",},
		[102] = {"Skybox",{"Change how the sky looks.",},},
		[103] = {"Inferno",{"Draw molotov covered inferno.",},},
		[104] = {"Grenade Tracer",{"Visualize predicted grenade trajectory.",},},
		[105] = {"Grenade Warning",{"Show predicted explosion warning.",},},
		[106] = {"Occluded",{"Material occluded by walls.",{[1] = "Off",[2] = "Flat",[3] = "Color",[4] = "Metallic",[5] = "Glow",[6] = "Pearlescent",[7] = "Bubble",},},},
		[107] = {"Visible",{"Visible material.",{[1] = "Off",[2] = "Flat",[3] = "Color",[4] = "Metallic",[5] = "Glow",[6] = "Pearlescent",[7] = "Bubble",[8] = "Textured",[9] = "Invisible",},},},
		[108] = {"Overlay",{"Apply over previous materials.",{[1] = "Off",[2] = "Wireframe",},},},
		[109] = {"Glow",{"Glow effect on model.",{[1] = "Off",[2] = "Color",[3] = "Health",},},},
		[110] = {"Occluded",{"Material occluded by walls.",{[1] = "Off",[2] = "Flat",[3] = "Color",[4] = "Metallic",[5] = "Glow",[6] = "Pearlescent",[7] = "Bubble",},},},
		[111] = {"Visible",{"Visible material.",{[1] = "Off",[2] = "Flat",[3] = "Color",[4] = "Metallic",[5] = "Glow",[6] = "Pearlescent",[7] = "Bubble",[8] = "Textured",[9] = "Invisible",},},},
		[112] = {"Overlay",{"Apply over previous materials.",{[1] = "Off",[2] = "Wireframe",},},},
		[113] = {"Glow",{"Glow effect on model.",{[1] = "Off",[2] = "Color",[3] = "Health",},},},
		[114] = {"Occluded",{"Material occluded by walls.",{[1] = "Off",[2] = "Flat",[3] = "Color",[4] = "Metallic",[5] = "Glow",[6] = "Pearlescent",[7] = "Bubble",},},},
		[115] = {"Visible",{"Visible material.",{[1] = "Off",[2] = "Flat",[3] = "Color",[4] = "Metallic",[5] = "Glow",[6] = "Pearlescent",[7] = "Bubble",[8] = "Textured",[9] = "Invisible",},},},
		[116] = {"Overlay",{"Apply over previous materials.",{[1] = "Off",[2] = "Wireframe",},},},
		[117] = {"Glow",{"Glow effect on model.",{[1] = "Off",[2] = "Color",[3] = "Health",},},},
		[118] = {"Occluded",{"Material occluded by walls.",{[1] = "Off",[2] = "Flat",[3] = "Color",[4] = "Metallic",[5] = "Glow",[6] = "Pearlescent",[7] = "Bubble",},},},
		[119] = {"Visible",{"Visible material.",{[1] = "Off",[2] = "Flat",[3] = "Color",[4] = "Metallic",[5] = "Glow",[6] = "Pearlescent",[7] = "Bubble",[8] = "Textured",[9] = "Invisible",},},},
		[120] = {"Overlay",{"Apply over previous materials.",{[1] = "Off",[2] = "Wireframe",},},},
		[121] = {"Glow",{"Glow effect on model.",{[1] = "Off",[2] = "Color",[3] = "Health",},},},
		[122] = {"Occluded",{"Material occluded by walls.",{[1] = "Off",[2] = "Flat",[3] = "Color",[4] = "Metallic",[5] = "Glow",[6] = "Pearlescent",[7] = "Bubble",},},},
		[123] = {"Visible",{"Visible material.",{[1] = "Off",[2] = "Flat",[3] = "Color",[4] = "Metallic",[5] = "Glow",[6] = "Pearlescent",[7] = "Bubble",[8] = "Textured",[9] = "Invisible",},},},
		[124] = {"Overlay",{"Apply over previous materials.",{[1] = "Off",[2] = "Wireframe",},},},
		[125] = {"Glow",{"Glow effect on model.",{[1] = "Off",[2] = "Color",[3] = "Health",},},},
		[126] = {"Occluded",{"Material occluded by walls.",{[1] = "Off",[2] = "Flat",[3] = "Color",[4] = "Metallic",[5] = "Glow",[6] = "Pearlescent",[7] = "Bubble",},},},
		[127] = {"Visible",{"Visible material.",{[1] = "Off",[2] = "Flat",[3] = "Color",[4] = "Metallic",[5] = "Glow",[6] = "Pearlescent",[7] = "Bubble",[8] = "Textured",[9] = "Invisible",},},},
		[128] = {"Overlay",{"Apply over previous materials.",{[1] = "Off",[2] = "Wireframe",},},},
		[129] = {"Glow",{"Glow effect on model.",{[1] = "Off",[2] = "Color",[3] = "Health",},},},
		[130] = {"Occluded",{"Material occluded by walls.",{[1] = "Off",[2] = "Flat",[3] = "Color",[4] = "Metallic",[5] = "Glow",[6] = "Pearlescent",[7] = "Bubble",},},},
		[131] = {"Visible",{"Visible material.",{[1] = "Off",[2] = "Flat",[3] = "Color",[4] = "Metallic",[5] = "Glow",[6] = "Pearlescent",[7] = "Bubble",[8] = "Textured",[9] = "Invisible",},},},
		[132] = {"Overlay",{"Apply over previous materials.",{[1] = "Off",[2] = "Wireframe",},},},
		[133] = {"Glow",{"Glow effect on model.",{[1] = "Off",[2] = "Color",[3] = "Health",},},},
		[134] = {"Occluded",{"Material occluded by walls.",{[1] = "Off",[2] = "Flat",[3] = "Color",[4] = "Metallic",[5] = "Glow",[6] = "Pearlescent",[7] = "Bubble",},},},
		[135] = {"Visible",{"Visible material.",{[1] = "Off",[2] = "Flat",[3] = "Color",[4] = "Metallic",[5] = "Glow",[6] = "Pearlescent",[7] = "Bubble",[8] = "Textured",[9] = "Invisible",},},},
		[136] = {"Overlay",{"Apply over previous materials.",{[1] = "Off",[2] = "Wireframe",},},},
		[137] = {"Glow",{"Glow effect on model.",{[1] = "Off",[2] = "Color",[3] = "Health",},},},
		[138] = {"Occluded",{"Material occluded by walls.",{[1] = "Off",[2] = "Flat",[3] = "Color",[4] = "Metallic",[5] = "Glow",[6] = "Pearlescent",[7] = "Bubble",},},},
		[139] = {"Visible",{"Visible material.",{[1] = "Off",[2] = "Flat",[3] = "Color",[4] = "Metallic",[5] = "Glow",[6] = "Pearlescent",[7] = "Bubble",[8] = "Textured",[9] = "Invisible",},},},
		[140] = {"Overlay",{"Apply over previous materials.",{[1] = "Off",[2] = "Wireframe",},},},
		[141] = {"Glow",{"Glow effect on model.",{[1] = "Off",[2] = "Color",[3] = "Health",},},},
		[142] = {"Occluded",{"Material occluded by walls.",{[1] = "Off",[2] = "Flat",[3] = "Color",[4] = "Metallic",[5] = "Glow",[6] = "Pearlescent",[7] = "Bubble",},},},
		[143] = {"Visible",{"Visible material.",{[1] = "Off",[2] = "Flat",[3] = "Color",[4] = "Metallic",[5] = "Glow",[6] = "Pearlescent",[7] = "Bubble",[8] = "Textured",[9] = "Invisible",},},},
		[144] = {"Overlay",{"Apply over previous materials.",{[1] = "Off",[2] = "Wireframe",},},},
		[145] = {"Glow",{"Glow effect on model.",{[1] = "Off",[2] = "Color",[3] = "Health",},},},
		[146] = {"Occluded",{"Material occluded by walls.",{[1] = "Off",[2] = "Flat",[3] = "Color",[4] = "Metallic",[5] = "Glow",[6] = "Pearlescent",[7] = "Bubble",},},},
		[147] = {"Visible",{"Visible material.",{[1] = "Off",[2] = "Flat",[3] = "Color",[4] = "Metallic",[5] = "Glow",[6] = "Pearlescent",[7] = "Bubble",[8] = "Textured",[9] = "Invisible",},},},
		[148] = {"Overlay",{"Apply over previous materials.",{[1] = "Off",[2] = "Wireframe",},},},
		[149] = {"Glow",{"Glow effect on model.",{[1] = "Off",[2] = "Color",[3] = "Health",},},},
		[150] = {"Occluded",{"Material occluded by walls.",{[1] = "Off",[2] = "Flat",[3] = "Color",[4] = "Metallic",[5] = "Glow",[6] = "Pearlescent",[7] = "Bubble",},},},
		[151] = {"Visible",{"Visible material.",{[1] = "Off",[2] = "Flat",[3] = "Color",[4] = "Metallic",[5] = "Glow",[6] = "Pearlescent",[7] = "Bubble",[8] = "Textured",[9] = "Invisible",},},},
		[152] = {"Overlay",{"Apply over previous materials.",{[1] = "Off",[2] = "Wireframe",},},},
		[153] = {"Glow",{"Glow effect on model.",{[1] = "Off",[2] = "Color",[3] = "Health",},},},
		[154] = {"Occluded",{"Material occluded by walls.",{[1] = "Off",[2] = "Flat",[3] = "Color",[4] = "Metallic",[5] = "Glow",[6] = "Pearlescent",[7] = "Bubble",},},},
		[155] = {"Visible",{"Visible material.",{[1] = "Off",[2] = "Flat",[3] = "Color",[4] = "Metallic",[5] = "Glow",[6] = "Pearlescent",[7] = "Bubble",[8] = "Textured",[9] = "Invisible",},},},
		[156] = {"Overlay",{"Apply over previous materials.",{[1] = "Off",[2] = "Wireframe",},},},
		[157] = {"Glow",{"Glow effect on model.",{[1] = "Off",[2] = "Color",[3] = "Health",},},},
		[158] = {"Occluded",{"Material occluded by walls.",{[1] = "Off",[2] = "Flat",[3] = "Color",[4] = "Metallic",[5] = "Glow",[6] = "Pearlescent",[7] = "Bubble",},},},
		[159] = {"Visible",{"Visible material.",{[1] = "Off",[2] = "Flat",[3] = "Color",[4] = "Metallic",[5] = "Glow",[6] = "Pearlescent",[7] = "Bubble",[8] = "Textured",[9] = "Invisible",},},},
		[160] = {"Overlay",{"Apply over previous materials.",{[1] = "Off",[2] = "Wireframe",},},},
		[161] = {"Glow",{"Glow effect on model.",{[1] = "Off",[2] = "Color",[3] = "Health",},},},
		[162] = {"Add",},
		[163] = {"Remove",},
		[164] = {"Item",{"Select weapon or model.",},},
		[165] = {"Paint Kits",{"Select skin of model.",},},
		[166] = {"Wear",{"Quality of item texture.",},},
		[167] = {"Seed",{"Seed of texture generation.",},},
		[168] = {"StatTrak",{"Kill counter of weapon.",},},
		[169] = {"Name",{"Custom name of item.",},},
		[170] = {"Radar",{"Display custom radar.",},},
		[171] = {"Radar Range",{"Set radar range.",},},
		[172] = {"Radar Transparency",{"Set radar transparency.",},},
		[173] = {"Crosshair",{"Display custom crosshair.",},},
		[174] = {"Crosshair Recoil",{"Draws the spot where your shots will go.",{[1] = "Off",[2] = "Line",[3] = "Fade",},},},
		[175] = {"Anti-OBS",{"Hide visuals from screen recorder.",},},
		[176] = {"Anti-Screenshot",{"Hide visuals from screenshots.",},},
		[177] = {"Preserve Killfeed",{"Preserve the killfeed.",},},
		[178] = {"Effects Removal",{"Disable selected effects.",},},
		[179] = {"Performance Options",{"Various options to improve game performance.",},},
		[180] = {"Anti-Untrusted",{"Restrict various features on Valve servers.",},},
		[181] = {"Bypass sv_pure",{"Allow custom models and materials from csgo directory.",},},
		[182] = {"Bypass sv_cheats",{"Bypass protected convars.",},},
		[183] = {"Unlock Steam Achievements",},
		[184] = {"Show hidden ConVars",},
		[185] = {"sv_maxunlag",{"Configure server-side max backtracking factor.",},},
		[186] = {"sv_maxusrcmdprocessticks",{"Configure server-side max lag factor.",},},
		[187] = {"Player List",{"Configure per player settings.",},},
		[188] = {"Show Spectators",{"See who is spectating you.",},},
		[189] = {"Show Ranks",{"Show rank of players.",},},
		[190] = {"Auto-Accept Match",{"Automatically Accept match.",},},
		[191] = {"Log Damage",{"Log damage dealt to enemies.",},},
		[192] = {"Log Purchases",{"Log purchases made by enemy team.",},},
		[193] = {"Log Console",{"Log console messages on screen.",},},
		[194] = {"Auto Jump",{"Select auto jump mode for bunnyhopping.",{[1] = "Off",[2] = "Perfect",[3] = "Legit",},},},
		[195] = {"Edge Jump",{"Jump right before falling of an edge.",},},
		[196] = {"Duck Jump",{"Reach higher by crouching while jumping.",},},
		[197] = {"Auto Jump-Bug",{"No fall damage when landing from a certain height.",},},
		[198] = {"Fast Duck",{"Exploit movement code to crouch quicker.",},},
		[199] = {"Slide Walk",{"Glitch animation to appear as sliding.",},},
		[200] = {"Enable",{"Automatically throw grenades/incendiary.",},},
		[201] = {"Grenade Distance",{"Distance from the target to autothrow the grenade.",},},
		[202] = {"Incendiary Distance",{"Distance from the target to autothrow the incendiary.",},},
		[203] = {"Enable",{"Enable autostrafer to gain more speed.",},},
		[204] = {"Air Strafe",{"Increases forward speed while jumping.",},},
		[205] = {"Strafe Mode",{"Select style of autostrafing.",{[1] = "Silent",[2] = "Normal",[3] = "Sideways",[4] = "W-",[5] = "Mouse",},},},
		[206] = {"Circle Strafe",{"Strafe in circles when pressing a key.",},},
		[207] = {"Snake Strafe",{"Strafe like a snake when pressing a key.",},},
		[208] = {"Retrack Speed",{"Autostrafe in direction on pressed movement keys.",},},
		[209] = {"WASD-Movement",{"Autostrafe in direction of pressed movement keys.",},},
		[210] = {"Enable",{"Enable lag effect.",},},
		[211] = {"On Key",{"Enable lag only when holding this key.",},},
		[212] = {"Type",{"Type or \"patern\" of lag",{[1] = "Normal",[2] = "Adaptive",[3] = "Random",[4] = "Switch",},},},
		[213] = {"Factor",{"How many commands will be choked.",},},
		[214] = {"Conditions",{"Configure fakelag options.",},},
		[215] = {"Enable",{"Enable latency modifier.",},},
		[216] = {"On Key",{"Increase latency only when holding this key.",},},
		[217] = {"Amount",{"Absolute latency to achieve.",},},
		[218] = {"Steal Name",{"Streal other player name, limited to 5 times.",},},
		[219] = {"Invisible Name",{"Make your name invisible.",},},
		[220] = {"Chat Spam",{"Advertise AIMWARE in chat.",},},
		[221] = {"Clantag Changer",{"Put AIMWARE as your clantag.",},},
		[222] = {"Name",{"Create or rename configuration",},},
		[223] = {"Create",},
		[224] = {"Rename",},
		[225] = {"Load",},
		[226] = {"Save",},
		[227] = {"Reset",},
		[228] = {"Delete",},
		[229] = {"Export To Clipboard",},
		[230] = {"Import From Clipboard",},
		[231] = {"Set As Default",},
		[232] = {"Refresh List",},
		[233] = {"Name",{"Create or rename script",},},
		[234] = {"Create",},
		[235] = {"Rename",},
		[236] = {"Edit (BETA)",},
		[237] = {"Load",},
		[238] = {"Unload",},
		[239] = {"Reset Lua State",},
		[240] = {"Delete",},
		[241] = {"Set As Autorun",},
		[242] = {"Refresh List",},
		[243] = {"Background",},
		[244] = {"Line",},
		[245] = {"Text",},
		[246] = {"Background",},
		[247] = {"Active",},
		[248] = {"Active Shadow",},
		[249] = {"Text",},
		[250] = {"Background",},
		[251] = {"Text",},
		[252] = {"Background #1",},
		[253] = {"Background #2",},
		[254] = {"Border",},
		[255] = {"Text",},
		[256] = {"Text Active",},
		[257] = {"Active Shadow",},
		[258] = {"Tab Active Decorator",},
		[259] = {"Tab Active Background",},
		[260] = {"Open Menu Key",{"Bind for main menu toggle.",},},
		[261] = {"Open Console Key",{"Console for more customization.",},},
		[262] = {"Dpi Scale",{"Scale the UI size by this amount.",},},
		[263] = {"Open Settings Folder",},
		[264] = {"菜单翻译",{"中文翻译By An QQ:2926669800 QID:AnAIMWARE",},},
	},
	[6] = {
		[1] = {"Hitbox Advance Multipler",{"How fast should the aimbot switch to the next target.",},},
		[2] = {"Nearest To Crosshair",{"Priority hitbox nearest to crosshair first.",},},
		[3] = {"Hitbox Advance Multipler",{"How fast should the aimbot switch to the next target.",},},
		[4] = {"Nearest To Crosshair",{"Priority hitbox nearest to crosshair first.",},},
		[5] = {"Hitbox Advance Multipler",{"How fast should the aimbot switch to the next target.",},},
		[6] = {"Nearest To Crosshair",{"Priority hitbox nearest to crosshair first.",},},
		[7] = {"Hitbox Advance Multipler",{"How fast should the aimbot switch to the next target.",},},
		[8] = {"Nearest To Crosshair",{"Priority hitbox nearest to crosshair first.",},},
		[9] = {"Hitbox Advance Multipler",{"How fast should the aimbot switch to the next target.",},},
		[10] = {"Nearest To Crosshair",{"Priority hitbox nearest to crosshair first.",},},
		[11] = {"Hitbox Advance Multipler",{"How fast should the aimbot switch to the next target.",},},
		[12] = {"Nearest To Crosshair",{"Priority hitbox nearest to crosshair first.",},},
		[13] = {"Hitbox Advance Multipler",{"How fast should the aimbot switch to the next target.",},},
		[14] = {"Nearest To Crosshair",{"Priority hitbox nearest to crosshair first.",},},
		[15] = {"Hitbox Advance Multipler",{"How fast should the aimbot switch to the next target.",},},
		[16] = {"Nearest To Crosshair",{"Priority hitbox nearest to crosshair first.",},},
		[17] = {"Hitbox Advance Multipler",{"How fast should the aimbot switch to the next target.",},},
		[18] = {"Nearest To Crosshair",{"Priority hitbox nearest to crosshair first.",},},
		[19] = {"Hitbox Advance Multipler",{"How fast should the aimbot switch to the next target.",},},
		[20] = {"Nearest To Crosshair",{"Priority hitbox nearest to crosshair first.",},},
		[21] = {"Hitbox Advance Multipler",{"How fast should the aimbot switch to the next target.",},},
		[22] = {"Nearest To Crosshair",{"Priority hitbox nearest to crosshair first.",},},
		[23] = {"Trigger Delay",{"Delay shot after trigger lock.",},},
		[24] = {"Trigger Burst",{"Keep firing after trigger lock.",},},
		[25] = {"Hit Chance",{"Minimum chance to hit before aimbot shoots.",},},
		[26] = {"Anti-Recoil",{"Counter weapon recoil for higher accuracy.",},},
		[27] = {"Trigger Delay",{"Delay shot after trigger lock.",},},
		[28] = {"Trigger Burst",{"Keep firing after trigger lock.",},},
		[29] = {"Hit Chance",{"Minimum chance to hit before aimbot shoots.",},},
		[30] = {"Anti-Recoil",{"Counter weapon recoil for higher accuracy.",},},
		[31] = {"Trigger Delay",{"Delay shot after trigger lock.",},},
		[32] = {"Trigger Burst",{"Keep firing after trigger lock.",},},
		[33] = {"Hit Chance",{"Minimum chance to hit before aimbot shoots.",},},
		[34] = {"Anti-Recoil",{"Counter weapon recoil for higher accuracy.",},},
		[35] = {"Trigger Delay",{"Delay shot after trigger lock.",},},
		[36] = {"Trigger Burst",{"Keep firing after trigger lock.",},},
		[37] = {"Hit Chance",{"Minimum chance to hit before aimbot shoots.",},},
		[38] = {"Anti-Recoil",{"Counter weapon recoil for higher accuracy.",},},
		[39] = {"Trigger Delay",{"Delay shot after trigger lock.",},},
		[40] = {"Trigger Burst",{"Keep firing after trigger lock.",},},
		[41] = {"Hit Chance",{"Minimum chance to hit before aimbot shoots.",},},
		[42] = {"Anti-Recoil",{"Counter weapon recoil for higher accuracy.",},},
		[43] = {"Trigger Delay",{"Delay shot after trigger lock.",},},
		[44] = {"Trigger Burst",{"Keep firing after trigger lock.",},},
		[45] = {"Hit Chance",{"Minimum chance to hit before aimbot shoots.",},},
		[46] = {"Anti-Recoil",{"Counter weapon recoil for higher accuracy.",},},
		[47] = {"Trigger Delay",{"Delay shot after trigger lock.",},},
		[48] = {"Trigger Burst",{"Keep firing after trigger lock.",},},
		[49] = {"Hit Chance",{"Minimum chance to hit before aimbot shoots.",},},
		[50] = {"Anti-Recoil",{"Counter weapon recoil for higher accuracy.",},},
		[51] = {"Trigger Delay",{"Delay shot after trigger lock.",},},
		[52] = {"Trigger Burst",{"Keep firing after trigger lock.",},},
		[53] = {"Hit Chance",{"Minimum chance to hit before aimbot shoots.",},},
		[54] = {"Anti-Recoil",{"Counter weapon recoil for higher accuracy.",},},
		[55] = {"Trigger Delay",{"Delay shot after trigger lock.",},},
		[56] = {"Trigger Burst",{"Keep firing after trigger lock.",},},
		[57] = {"Hit Chance",{"Minimum chance to hit before aimbot shoots.",},},
		[58] = {"Anti-Recoil",{"Counter weapon recoil for higher accuracy.",},},
		[59] = {"Trigger Delay",{"Delay shot after trigger lock.",},},
		[60] = {"Trigger Burst",{"Keep firing after trigger lock.",},},
		[61] = {"Hit Chance",{"Minimum chance to hit before aimbot shoots.",},},
		[62] = {"Anti-Recoil",{"Counter weapon recoil for higher accuracy.",},},
		[63] = {"Trigger Delay",{"Delay shot after trigger lock.",},},
		[64] = {"Trigger Burst",{"Keep firing after trigger lock.",},},
		[65] = {"Hit Chance",{"Minimum chance to hit before aimbot shoots.",},},
		[66] = {"Anti-Recoil",{"Counter weapon recoil for higher accuracy.",},},
		[67] = {"Smooth Factor",{"Smooth out aimbot movement",},},
		[68] = {"Smooth Method",{"Method to use for smooth movement.",{[1] = "Dynamic",[2] = "Static",},},},
		[69] = {"Randomize Factor",{"Randomize aimbot target position.",},},
		[70] = {"Curve Factor",{"How non-linear the movement will be.",},},
		[71] = {"Smooth Factor",{"Smooth out aimbot movement",},},
		[72] = {"Smooth Method",{"Method to use for smooth movement.",{[1] = "Dynamic",[2] = "Static",},},},
		[73] = {"Randomize Factor",{"Randomize aimbot target position.",},},
		[74] = {"Curve Factor",{"How non-linear the movement will be.",},},
		[75] = {"Smooth Factor",{"Smooth out aimbot movement",},},
		[76] = {"Smooth Method",{"Method to use for smooth movement.",{[1] = "Dynamic",[2] = "Static",},},},
		[77] = {"Randomize Factor",{"Randomize aimbot target position.",},},
		[78] = {"Curve Factor",{"How non-linear the movement will be.",},},
		[79] = {"Smooth Factor",{"Smooth out aimbot movement",},},
		[80] = {"Smooth Method",{"Method to use for smooth movement.",{[1] = "Dynamic",[2] = "Static",},},},
		[81] = {"Randomize Factor",{"Randomize aimbot target position.",},},
		[82] = {"Curve Factor",{"How non-linear the movement will be.",},},
		[83] = {"Smooth Factor",{"Smooth out aimbot movement",},},
		[84] = {"Smooth Method",{"Method to use for smooth movement.",{[1] = "Dynamic",[2] = "Static",},},},
		[85] = {"Randomize Factor",{"Randomize aimbot target position.",},},
		[86] = {"Curve Factor",{"How non-linear the movement will be.",},},
		[87] = {"Smooth Factor",{"Smooth out aimbot movement",},},
		[88] = {"Smooth Method",{"Method to use for smooth movement.",{[1] = "Dynamic",[2] = "Static",},},},
		[89] = {"Randomize Factor",{"Randomize aimbot target position.",},},
		[90] = {"Curve Factor",{"How non-linear the movement will be.",},},
		[91] = {"Smooth Factor",{"Smooth out aimbot movement",},},
		[92] = {"Smooth Method",{"Method to use for smooth movement.",{[1] = "Dynamic",[2] = "Static",},},},
		[93] = {"Randomize Factor",{"Randomize aimbot target position.",},},
		[94] = {"Curve Factor",{"How non-linear the movement will be.",},},
		[95] = {"Smooth Factor",{"Smooth out aimbot movement",},},
		[96] = {"Smooth Method",{"Method to use for smooth movement.",{[1] = "Dynamic",[2] = "Static",},},},
		[97] = {"Randomize Factor",{"Randomize aimbot target position.",},},
		[98] = {"Curve Factor",{"How non-linear the movement will be.",},},
		[99] = {"Smooth Factor",{"Smooth out aimbot movement",},},
		[100] = {"Smooth Method",{"Method to use for smooth movement.",{[1] = "Dynamic",[2] = "Static",},},},
		[101] = {"Randomize Factor",{"Randomize aimbot target position.",},},
		[102] = {"Curve Factor",{"How non-linear the movement will be.",},},
		[103] = {"Smooth Factor",{"Smooth out aimbot movement",},},
		[104] = {"Smooth Method",{"Method to use for smooth movement.",{[1] = "Dynamic",[2] = "Static",},},},
		[105] = {"Randomize Factor",{"Randomize aimbot target position.",},},
		[106] = {"Curve Factor",{"How non-linear the movement will be.",},},
		[107] = {"Smooth Factor",{"Smooth out aimbot movement",},},
		[108] = {"Smooth Method",{"Method to use for smooth movement.",{[1] = "Dynamic",[2] = "Static",},},},
		[109] = {"Randomize Factor",{"Randomize aimbot target position.",},},
		[110] = {"Curve Factor",{"How non-linear the movement will be.",},},
		[111] = {"Auto Wall",{"Shoot through penetrable walls.",},},
		[112] = {"Through Smoke",{"Fire through smoke.",},},
		[113] = {"Auto Wall",{"Shoot through penetrable walls.",},},
		[114] = {"Through Smoke",{"Fire through smoke.",},},
		[115] = {"Auto Wall",{"Shoot through penetrable walls.",},},
		[116] = {"Through Smoke",{"Fire through smoke.",},},
		[117] = {"Auto Wall",{"Shoot through penetrable walls.",},},
		[118] = {"Through Smoke",{"Fire through smoke.",},},
		[119] = {"Auto Wall",{"Shoot through penetrable walls.",},},
		[120] = {"Through Smoke",{"Fire through smoke.",},},
		[121] = {"Auto Wall",{"Shoot through penetrable walls.",},},
		[122] = {"Through Smoke",{"Fire through smoke.",},},
		[123] = {"Auto Wall",{"Shoot through penetrable walls.",},},
		[124] = {"Through Smoke",{"Fire through smoke.",},},
		[125] = {"Auto Wall",{"Shoot through penetrable walls.",},},
		[126] = {"Through Smoke",{"Fire through smoke.",},},
		[127] = {"Auto Wall",{"Shoot through penetrable walls.",},},
		[128] = {"Through Smoke",{"Fire through smoke.",},},
		[129] = {"Auto Wall",{"Shoot through penetrable walls.",},},
		[130] = {"Through Smoke",{"Fire through smoke.",},},
		[131] = {"Auto Wall",{"Shoot through penetrable walls.",},},
		[132] = {"Through Smoke",{"Fire through smoke.",},},
		[133] = {"Recoil Control System",{"Smoothly counter weapon recoil.",},},
		[134] = {"Standalone Recoil Control",{"Enable RCS while aiming freely.",},},
		[135] = {"Horizontal Recoil",{"How much of horizontal recoil will be countered.",},},
		[136] = {"Vertical Recoil",{"How much of vertical recoil will be countered.",},},
		[137] = {"Recoil Control System",{"Smoothly counter weapon recoil.",},},
		[138] = {"Standalone Recoil Control",{"Enable RCS while aiming freely.",},},
		[139] = {"Horizontal Recoil",{"How much of horizontal recoil will be countered.",},},
		[140] = {"Vertical Recoil",{"How much of vertical recoil will be countered.",},},
		[141] = {"Recoil Control System",{"Smoothly counter weapon recoil.",},},
		[142] = {"Standalone Recoil Control",{"Enable RCS while aiming freely.",},},
		[143] = {"Horizontal Recoil",{"How much of horizontal recoil will be countered.",},},
		[144] = {"Vertical Recoil",{"How much of vertical recoil will be countered.",},},
		[145] = {"Recoil Control System",{"Smoothly counter weapon recoil.",},},
		[146] = {"Standalone Recoil Control",{"Enable RCS while aiming freely.",},},
		[147] = {"Horizontal Recoil",{"How much of horizontal recoil will be countered.",},},
		[148] = {"Vertical Recoil",{"How much of vertical recoil will be countered.",},},
		[149] = {"Recoil Control System",{"Smoothly counter weapon recoil.",},},
		[150] = {"Standalone Recoil Control",{"Enable RCS while aiming freely.",},},
		[151] = {"Horizontal Recoil",{"How much of horizontal recoil will be countered.",},},
		[152] = {"Vertical Recoil",{"How much of vertical recoil will be countered.",},},
		[153] = {"Recoil Control System",{"Smoothly counter weapon recoil.",},},
		[154] = {"Standalone Recoil Control",{"Enable RCS while aiming freely.",},},
		[155] = {"Horizontal Recoil",{"How much of horizontal recoil will be countered.",},},
		[156] = {"Vertical Recoil",{"How much of vertical recoil will be countered.",},},
		[157] = {"Recoil Control System",{"Smoothly counter weapon recoil.",},},
		[158] = {"Standalone Recoil Control",{"Enable RCS while aiming freely.",},},
		[159] = {"Horizontal Recoil",{"How much of horizontal recoil will be countered.",},},
		[160] = {"Vertical Recoil",{"How much of vertical recoil will be countered.",},},
		[161] = {"Recoil Control System",{"Smoothly counter weapon recoil.",},},
		[162] = {"Standalone Recoil Control",{"Enable RCS while aiming freely.",},},
		[163] = {"Horizontal Recoil",{"How much of horizontal recoil will be countered.",},},
		[164] = {"Vertical Recoil",{"How much of vertical recoil will be countered.",},},
		[165] = {"Recoil Control System",{"Smoothly counter weapon recoil.",},},
		[166] = {"Standalone Recoil Control",{"Enable RCS while aiming freely.",},},
		[167] = {"Horizontal Recoil",{"How much of horizontal recoil will be countered.",},},
		[168] = {"Vertical Recoil",{"How much of vertical recoil will be countered.",},},
		[169] = {"Recoil Control System",{"Smoothly counter weapon recoil.",},},
		[170] = {"Standalone Recoil Control",{"Enable RCS while aiming freely.",},},
		[171] = {"Horizontal Recoil",{"How much of horizontal recoil will be countered.",},},
		[172] = {"Vertical Recoil",{"How much of vertical recoil will be countered.",},},
		[173] = {"Recoil Control System",{"Smoothly counter weapon recoil.",},},
		[174] = {"Standalone Recoil Control",{"Enable RCS while aiming freely.",},},
		[175] = {"Horizontal Recoil",{"How much of horizontal recoil will be countered.",},},
		[176] = {"Vertical Recoil",{"How much of vertical recoil will be countered.",},},
		[177] = {"Minimum FOV Range",{"Minimum field of view for aim lock.",},},
		[178] = {"Maximum FOV Range",{"Maximum field of view for aim lock.",},},
		[179] = {"Target Switch Delay",{"Time aimbot will wait before switching targer.",},},
		[180] = {"First Shot Delay",{"Time till aimbot fires first shot.",},},
		[181] = {"Minimum FOV Range",{"Minimum field of view for aim lock.",},},
		[182] = {"Maximum FOV Range",{"Maximum field of view for aim lock.",},},
		[183] = {"Target Switch Delay",{"Time aimbot will wait before switching targer.",},},
		[184] = {"First Shot Delay",{"Time till aimbot fires first shot.",},},
		[185] = {"Minimum FOV Range",{"Minimum field of view for aim lock.",},},
		[186] = {"Maximum FOV Range",{"Maximum field of view for aim lock.",},},
		[187] = {"Target Switch Delay",{"Time aimbot will wait before switching targer.",},},
		[188] = {"First Shot Delay",{"Time till aimbot fires first shot.",},},
		[189] = {"Minimum FOV Range",{"Minimum field of view for aim lock.",},},
		[190] = {"Maximum FOV Range",{"Maximum field of view for aim lock.",},},
		[191] = {"Target Switch Delay",{"Time aimbot will wait before switching targer.",},},
		[192] = {"First Shot Delay",{"Time till aimbot fires first shot.",},},
		[193] = {"Minimum FOV Range",{"Minimum field of view for aim lock.",},},
		[194] = {"Maximum FOV Range",{"Maximum field of view for aim lock.",},},
		[195] = {"Target Switch Delay",{"Time aimbot will wait before switching targer.",},},
		[196] = {"First Shot Delay",{"Time till aimbot fires first shot.",},},
		[197] = {"Minimum FOV Range",{"Minimum field of view for aim lock.",},},
		[198] = {"Maximum FOV Range",{"Maximum field of view for aim lock.",},},
		[199] = {"Target Switch Delay",{"Time aimbot will wait before switching targer.",},},
		[200] = {"First Shot Delay",{"Time till aimbot fires first shot.",},},
		[201] = {"Minimum FOV Range",{"Minimum field of view for aim lock.",},},
		[202] = {"Maximum FOV Range",{"Maximum field of view for aim lock.",},},
		[203] = {"Target Switch Delay",{"Time aimbot will wait before switching targer.",},},
		[204] = {"First Shot Delay",{"Time till aimbot fires first shot.",},},
		[205] = {"Minimum FOV Range",{"Minimum field of view for aim lock.",},},
		[206] = {"Maximum FOV Range",{"Maximum field of view for aim lock.",},},
		[207] = {"Target Switch Delay",{"Time aimbot will wait before switching targer.",},},
		[208] = {"First Shot Delay",{"Time till aimbot fires first shot.",},},
		[209] = {"Minimum FOV Range",{"Minimum field of view for aim lock.",},},
		[210] = {"Maximum FOV Range",{"Maximum field of view for aim lock.",},},
		[211] = {"Target Switch Delay",{"Time aimbot will wait before switching targer.",},},
		[212] = {"First Shot Delay",{"Time till aimbot fires first shot.",},},
		[213] = {"Minimum FOV Range",{"Minimum field of view for aim lock.",},},
		[214] = {"Maximum FOV Range",{"Maximum field of view for aim lock.",},},
		[215] = {"Target Switch Delay",{"Time aimbot will wait before switching targer.",},},
		[216] = {"First Shot Delay",{"Time till aimbot fires first shot.",},},
		[217] = {"Minimum FOV Range",{"Minimum field of view for aim lock.",},},
		[218] = {"Maximum FOV Range",{"Maximum field of view for aim lock.",},},
		[219] = {"Target Switch Delay",{"Time aimbot will wait before switching targer.",},},
		[220] = {"First Shot Delay",{"Time till aimbot fires first shot.",},},
		[221] = {"Hit Chance",{"Minimum chance to hit before aimbot shoots.",},},
		[222] = {"Min Damage",{"Minimum damage required after wall penetration.",},},
		[223] = {"Anti-Recoil",{"Counter weapon recoil for higher accuracy.",},},
		[224] = {"Double Fire",{"Shoot two bullets at once.",{[1] = "Off",[2] = "Shift",[3] = "Rapid",},},},
		[225] = {"Double Fire Indicator",{"Show the Double Fire indicator.",},},
		[226] = {"Double Fire Hit Chance",{"Minimum chance to hit for second shot.",},},
		[227] = {"Hit Chance",{"Minimum chance to hit before aimbot shoots.",},},
		[228] = {"Min Damage",{"Minimum damage required after wall penetration.",},},
		[229] = {"Anti-Recoil",{"Counter weapon recoil for higher accuracy.",},},
		[230] = {"Hit Chance",{"Minimum chance to hit before aimbot shoots.",},},
		[231] = {"Min Damage",{"Minimum damage required after wall penetration.",},},
		[232] = {"Anti-Recoil",{"Counter weapon recoil for higher accuracy.",},},
		[233] = {"Double Fire",{"Shoot two bullets at once.",{[1] = "Off",[2] = "Shift",[3] = "Rapid",},},},
		[234] = {"Double Fire Indicator",{"Show the Double Fire indicator.",},},
		[235] = {"Double Fire Hit Chance",{"Minimum chance to hit for second shot.",},},
		[236] = {"Hit Chance",{"Minimum chance to hit before aimbot shoots.",},},
		[237] = {"Min Damage",{"Minimum damage required after wall penetration.",},},
		[238] = {"Anti-Recoil",{"Counter weapon recoil for higher accuracy.",},},
		[239] = {"Double Fire",{"Shoot two bullets at once.",{[1] = "Off",[2] = "Shift",[3] = "Rapid",},},},
		[240] = {"Double Fire Indicator",{"Show the Double Fire indicator.",},},
		[241] = {"Double Fire Hit Chance",{"Minimum chance to hit for second shot.",},},
		[242] = {"Hit Chance",{"Minimum chance to hit before aimbot shoots.",},},
		[243] = {"Min Damage",{"Minimum damage required after wall penetration.",},},
		[244] = {"Anti-Recoil",{"Counter weapon recoil for higher accuracy.",},},
		[245] = {"Double Fire",{"Shoot two bullets at once.",{[1] = "Off",[2] = "Shift",[3] = "Rapid",},},},
		[246] = {"Double Fire Indicator",{"Show the Double Fire indicator.",},},
		[247] = {"Double Fire Hit Chance",{"Minimum chance to hit for second shot.",},},
		[248] = {"Hit Chance",{"Minimum chance to hit before aimbot shoots.",},},
		[249] = {"Min Damage",{"Minimum damage required after wall penetration.",},},
		[250] = {"Anti-Recoil",{"Counter weapon recoil for higher accuracy.",},},
		[251] = {"Double Fire",{"Shoot two bullets at once.",{[1] = "Off",[2] = "Shift",[3] = "Rapid",},},},
		[252] = {"Double Fire Indicator",{"Show the Double Fire indicator.",},},
		[253] = {"Double Fire Hit Chance",{"Minimum chance to hit for second shot.",},},
		[254] = {"Hit Chance",{"Minimum chance to hit before aimbot shoots.",},},
		[255] = {"Min Damage",{"Minimum damage required after wall penetration.",},},
		[256] = {"Anti-Recoil",{"Counter weapon recoil for higher accuracy.",},},
		[257] = {"Double Fire",{"Shoot two bullets at once.",{[1] = "Off",[2] = "Shift",[3] = "Rapid",},},},
		[258] = {"Double Fire Indicator",{"Show the Double Fire indicator.",},},
		[259] = {"Double Fire Hit Chance",{"Minimum chance to hit for second shot.",},},
		[260] = {"Hit Chance",{"Minimum chance to hit before aimbot shoots.",},},
		[261] = {"Min Damage",{"Minimum damage required after wall penetration.",},},
		[262] = {"Anti-Recoil",{"Counter weapon recoil for higher accuracy.",},},
		[263] = {"Hit Chance",{"Minimum chance to hit before aimbot shoots.",},},
		[264] = {"Min Damage",{"Minimum damage required after wall penetration.",},},
		[265] = {"Anti-Recoil",{"Counter weapon recoil for higher accuracy.",},},
		[266] = {"Double Fire",{"Shoot two bullets at once.",{[1] = "Off",[2] = "Shift",[3] = "Rapid",},},},
		[267] = {"Double Fire Indicator",{"Show the Double Fire indicator.",},},
		[268] = {"Double Fire Hit Chance",{"Minimum chance to hit for second shot.",},},
		[269] = {"Hit Chance",{"Minimum chance to hit before aimbot shoots.",},},
		[270] = {"Min Damage",{"Minimum damage required after wall penetration.",},},
		[271] = {"Anti-Recoil",{"Counter weapon recoil for higher accuracy.",},},
		[272] = {"Hit Chance",{"Minimum chance to hit before aimbot shoots.",},},
		[273] = {"Min Damage",{"Minimum damage required after wall penetration.",},},
		[274] = {"Anti-Recoil",{"Counter weapon recoil for higher accuracy.",},},
		[275] = {"Double Fire",{"Shoot two bullets at once.",{[1] = "Off",[2] = "Shift",[3] = "Rapid",},},},
		[276] = {"Double Fire Indicator",{"Show the Double Fire indicator.",},},
		[277] = {"Double Fire Hit Chance",{"Minimum chance to hit for second shot.",},},
		[278] = {"Auto Stop",{"Counter strafe when shooting to lower inaccuracy.",},},
		[279] = {"Auto Stop Options",},
		[280] = {"Auto Stop",{"Counter strafe when shooting to lower inaccuracy.",},},
		[281] = {"Auto Stop Options",},
		[282] = {"Auto Stop",{"Counter strafe when shooting to lower inaccuracy.",},},
		[283] = {"Auto Stop Options",},
		[284] = {"Auto Stop",{"Counter strafe when shooting to lower inaccuracy.",},},
		[285] = {"Auto Stop Options",},
		[286] = {"Auto Stop",{"Counter strafe when shooting to lower inaccuracy.",},},
		[287] = {"Auto Stop Options",},
		[288] = {"Auto Stop",{"Counter strafe when shooting to lower inaccuracy.",},},
		[289] = {"Auto Stop Options",},
		[290] = {"Auto Stop",{"Counter strafe when shooting to lower inaccuracy.",},},
		[291] = {"Auto Stop Options",},
		[292] = {"Auto Stop",{"Counter strafe when shooting to lower inaccuracy.",},},
		[293] = {"Auto Stop Options",},
		[294] = {"Auto Stop",{"Counter strafe when shooting to lower inaccuracy.",},},
		[295] = {"Auto Stop Options",},
		[296] = {"Auto Stop",{"Counter strafe when shooting to lower inaccuracy.",},},
		[297] = {"Auto Stop Options",},
		[298] = {"Auto Stop",{"Counter strafe when shooting to lower inaccuracy.",},},
		[299] = {"Auto Stop Options",},
		[300] = {"Auto Wall",{"Shoot through penetrable walls.",},},
		[301] = {"Bodyaim",{"Configure bodyaim prioritization.",},},
		[302] = {"Prefer Safe Point",{"Prefer overlapped hitbox points.",},},
        [303] = {"Force Safe Point",{"Wait for overlapped hitbox points.",},},
        [304] = {"Force Safe Point On Limbs",{"Wait for overlapped hitbox points on limbs.",},},
		[305] = {"Auto Wall",{"Shoot through penetrable walls.",},},
		[306] = {"Bodyaim",{"Configure bodyaim prioritization.",},},
		[307] = {"Prefer Safe Point",{"Prefer overlapped hitbox points.",},},
        [308] = {"Force Safe Point",{"Wait for overlapped hitbox points.",},},
        [309] = {"Force Safe Point On Limbs",{"Wait for overlapped hitbox points on limbs.",},},
		[310] = {"Auto Wall",{"Shoot through penetrable walls.",},},
		[311] = {"Bodyaim",{"Configure bodyaim prioritization.",},},
		[312] = {"Prefer Safe Point",{"Prefer overlapped hitbox points.",},},
        [313] = {"Force Safe Point",{"Wait for overlapped hitbox points.",},},
        [314] = {"Force Safe Point On Limbs",{"Wait for overlapped hitbox points on limbs.",},},
		[315] = {"Auto Wall",{"Shoot through penetrable walls.",},},
		[316] = {"Bodyaim",{"Configure bodyaim prioritization.",},},
		[317] = {"Prefer Safe Point",{"Prefer overlapped hitbox points.",},},
        [318] = {"Force Safe Point",{"Wait for overlapped hitbox points.",},},
        [319] = {"Force Safe Point On Limbs",{"Wait for overlapped hitbox points on limbs.",},},
		[320] = {"Auto Wall",{"Shoot through penetrable walls.",},},
		[321] = {"Bodyaim",{"Configure bodyaim prioritization.",},},
		[322] = {"Prefer Safe Point",{"Prefer overlapped hitbox points.",},},
        [323] = {"Force Safe Point",{"Wait for overlapped hitbox points.",},},
        [324] = {"Force Safe Point On Limbs",{"Wait for overlapped hitbox points on limbs.",},},
		[325] = {"Auto Wall",{"Shoot through penetrable walls.",},},
		[326] = {"Bodyaim",{"Configure bodyaim prioritization.",},},
		[327] = {"Prefer Safe Point",{"Prefer overlapped hitbox points.",},},
        [328] = {"Force Safe Point",{"Wait for overlapped hitbox points.",},},
        [329] = {"Force Safe Point On Limbs",{"Wait for overlapped hitbox points on limbs.",},},
		[330] = {"Auto Wall",{"Shoot through penetrable walls.",},},
		[331] = {"Bodyaim",{"Configure bodyaim prioritization.",},},
		[332] = {"Prefer Safe Point",{"Prefer overlapped hitbox points.",},},
        [333] = {"Force Safe Point",{"Wait for overlapped hitbox points.",},},
        [334] = {"Force Safe Point On Limbs",{"Wait for overlapped hitbox points on limbs.",},},
		[335] = {"Auto Wall",{"Shoot through penetrable walls.",},},
		[336] = {"Bodyaim",{"Configure bodyaim prioritization.",},},
		[337] = {"Prefer Safe Point",{"Prefer overlapped hitbox points.",},},
        [338] = {"Force Safe Point",{"Wait for overlapped hitbox points.",},},
        [339] = {"Force Safe Point On Limbs",{"Wait for overlapped hitbox points on limbs.",},},
		[340] = {"Auto Wall",{"Shoot through penetrable walls.",},},
		[341] = {"Bodyaim",{"Configure bodyaim prioritization.",},},
		[342] = {"Prefer Safe Point",{"Prefer overlapped hitbox points.",},},
        [343] = {"Force Safe Point",{"Wait for overlapped hitbox points.",},},
        [344] = {"Force Safe Point On Limbs",{"Wait for overlapped hitbox points on limbs.",},},
		[345] = {"Auto Wall",{"Shoot through penetrable walls.",},},
		[346] = {"Bodyaim",{"Configure bodyaim prioritization.",},},
		[347] = {"Prefer Safe Point",{"Prefer overlapped hitbox points.",},},
        [348] = {"Force Safe Point",{"Wait for overlapped hitbox points.",},},
		[349] = {"Force Safe Point On Limbs",{"Wait for overlapped hitbox points on limbs.",},},
		[350] = {"Auto Wall",{"Shoot through penetrable walls.",},},
		[351] = {"Bodyaim",{"Configure bodyaim prioritization.",},},
		[352] = {"Prefer Safe Point",{"Prefer overlapped hitbox points.",},},
        [353] = {"Force Safe Point",{"Wait for overlapped hitbox points.",},},
        [354] = {"Force Safe Point On Limbs",{"Wait for overlapped hitbox points on limbs.",},},
		[355] = {"Rotation Offset",},
		[356] = {"LBY Offset",},
		[357] = {"Spinbot Speed",},
		[358] = {"Rotation Offset",},
		[359] = {"LBY Offset",},
		[360] = {"Spinbot Speed",},
		[361] = {"Rotation Offset",},
		[362] = {"LBY Offset",},
		[363] = {"Spinbot Speed",},
		[364] = {"Disable On Use",{"Disable anti-aim when pressing the Use key.",},},
        [365] = {"Disable On Knife",{"Disable anti-aim when holding knife.",},},
        [366] = {"Disable On Grenade",{"Disable anti-aim when holding a grenade.",},},
        [367] = {"During Freeze Time",{"Disable anti-aim at the beginning of a round.",},},
		[368] = {"At Edges",{"Apply left/right direction based on nearby walls.",},},
		[369] = {"At Targets",{"Always face nearby enemies direction.",},},
		[370] = {"Bar",},
		[371] = {"Number",},
		[372] = {"Defusing",},
		[373] = {"Planting",},
		[374] = {"Scoped",},
		[375] = {"Reloading",},
		[376] = {"Flashed",},
		[377] = {"Has Defuser",},
		[378] = {"Has C4",},
		[379] = {"Bar",},
		[380] = {"Number",},
		[381] = {"Defusing",},
		[382] = {"Planting",},
		[383] = {"Scoped",},
		[384] = {"Reloading",},
		[385] = {"Flashed",},
		[386] = {"Has Defuser",},
		[387] = {"Has C4",},
		[388] = {"Name",},
		[389] = {"Icon",},
		[390] = {"Detonate Timer",},
		[391] = {"Damage",},
		[392] = {"Grid",},
		[393] = {"Sound",},
		[394] = {"Marker",},
		[395] = {"Local",},
		[396] = {"Friendly",},
		[397] = {"Enemy",},
		[398] = {"Local",},
		[399] = {"Friendly",},
		[400] = {"Enemy",},
		[401] = {"Local",},
		[402] = {"Friendly",},
		[403] = {"Enemy",},
		[404] = {"Local",},
		[405] = {"Friendly",},
		[406] = {"Enemy",},
		[407] = {"No Flash",},
		[408] = {"No Smoke",},
		[409] = {"No Recoil",},
		[410] = {"No Scope",},
		[411] = {"No Scope Overlay",},
		[412] = {"No Scope Dirt",},
		[413] = {"No Sky",},
		[414] = {"No Fog",},
		[415] = {"No Post Processing",},
		[416] = {"No Render For Teammates",},
		[417] = {"No Render For Enemies",},
		[418] = {"No Render For Weapons",},
		[419] = {"No Render For Ragdolls",},
		[420] = {"Disable Far Models",},
		[421] = {"Local",},
		[422] = {"Friendly",},
		[423] = {"Enemy",},
		[424] = {"Peek",{"Lag your model behind wall when peeking.",},},
		[425] = {"While Standing",},
		[426] = {"While Moving",},
		[427] = {"While In Air",},
	},
	[7] = {
		[1] = {"Between Shots",{"Enable continuous auto stop between shots.",},},
		[2] = {"Early",{"Stop earlier for higher initial accuracy.",},},
		[3] = {"Slow Walk",{"Allows slow walk movement during auto stop.",},},
		[4] = {"Duck",{"Duck during auto stop to further increase accuracy.",},},
		[5] = {"In Molotov",{"Allow auto stop within Molotov.",},},
		[6] = {"Between Shots",{"Enable continuous auto stop between shots.",},},
		[7] = {"Early",{"Stop earlier for higher initial accuracy.",},},
		[8] = {"Slow Walk",{"Allows slow walk movement during auto stop.",},},
		[9] = {"Duck",{"Duck during auto stop to further increase accuracy.",},},
		[10] = {"In Molotov",{"Allow auto stop within Molotov.",},},
		[11] = {"Between Shots",{"Enable continuous auto stop between shots.",},},
		[12] = {"Early",{"Stop earlier for higher initial accuracy.",},},
		[13] = {"Slow Walk",{"Allows slow walk movement during auto stop.",},},
		[14] = {"Duck",{"Duck during auto stop to further increase accuracy.",},},
		[15] = {"In Molotov",{"Allow auto stop within Molotov.",},},
		[16] = {"Between Shots",{"Enable continuous auto stop between shots.",},},
		[17] = {"Early",{"Stop earlier for higher initial accuracy.",},},
		[18] = {"Slow Walk",{"Allows slow walk movement during auto stop.",},},
		[19] = {"Duck",{"Duck during auto stop to further increase accuracy.",},},
		[20] = {"In Molotov",{"Allow auto stop within Molotov.",},},
		[21] = {"Between Shots",{"Enable continuous auto stop between shots.",},},
		[22] = {"Early",{"Stop earlier for higher initial accuracy.",},},
		[23] = {"Slow Walk",{"Allows slow walk movement during auto stop.",},},
		[24] = {"Duck",{"Duck during auto stop to further increase accuracy.",},},
		[25] = {"In Molotov",{"Allow auto stop within Molotov.",},},
		[26] = {"Between Shots",{"Enable continuous auto stop between shots.",},},
		[27] = {"Early",{"Stop earlier for higher initial accuracy.",},},
		[28] = {"Slow Walk",{"Allows slow walk movement during auto stop.",},},
		[29] = {"Duck",{"Duck during auto stop to further increase accuracy.",},},
		[30] = {"In Molotov",{"Allow auto stop within Molotov.",},},
		[31] = {"Between Shots",{"Enable continuous auto stop between shots.",},},
		[32] = {"Early",{"Stop earlier for higher initial accuracy.",},},
		[33] = {"Slow Walk",{"Allows slow walk movement during auto stop.",},},
		[34] = {"Duck",{"Duck during auto stop to further increase accuracy.",},},
		[35] = {"In Molotov",{"Allow auto stop within Molotov.",},},
		[36] = {"Between Shots",{"Enable continuous auto stop between shots.",},},
		[37] = {"Early",{"Stop earlier for higher initial accuracy.",},},
		[38] = {"Slow Walk",{"Allows slow walk movement during auto stop.",},},
		[39] = {"Duck",{"Duck during auto stop to further increase accuracy.",},},
		[40] = {"In Molotov",{"Allow auto stop within Molotov.",},},
		[41] = {"Between Shots",{"Enable continuous auto stop between shots.",},},
		[42] = {"Early",{"Stop earlier for higher initial accuracy.",},},
		[43] = {"Slow Walk",{"Allows slow walk movement during auto stop.",},},
		[44] = {"Duck",{"Duck during auto stop to further increase accuracy.",},},
		[45] = {"In Molotov",{"Allow auto stop within Molotov.",},},
		[46] = {"Between Shots",{"Enable continuous auto stop between shots.",},},
		[47] = {"Early",{"Stop earlier for higher initial accuracy.",},},
		[48] = {"Slow Walk",{"Allows slow walk movement during auto stop.",},},
		[49] = {"Duck",{"Duck during auto stop to further increase accuracy.",},},
		[50] = {"In Molotov",{"Allow auto stop within Molotov.",},},
		[51] = {"Between Shots",{"Enable continuous auto stop between shots.",},},
		[52] = {"Early",{"Stop earlier for higher initial accuracy.",},},
		[53] = {"Slow Walk",{"Allows slow walk movement during auto stop.",},},
		[54] = {"Duck",{"Duck during auto stop to further increase accuracy.",},},
		[55] = {"In Molotov",{"Allow auto stop within Molotov.",},},
		[56] = {"Force",{"Always prioritize bodyaim.",},},
		[57] = {"Lethal",{"Bodyaim when shot will be lethal.",},},
		[58] = {"On Shot",{"Bodyaim when enemy is shooting.",},},
		[59] = {"No Head Safepoint",{"Bodyaim when head hitboxes do not overlap.",},},
		[60] = {"Force",{"Always prioritize bodyaim.",},},
		[61] = {"Lethal",{"Bodyaim when shot will be lethal.",},},
		[62] = {"On Shot",{"Bodyaim when enemy is shooting.",},},
		[63] = {"No Head Safepoint",{"Bodyaim when head hitboxes do not overlap.",},},
		[64] = {"Force",{"Always prioritize bodyaim.",},},
		[65] = {"Lethal",{"Bodyaim when shot will be lethal.",},},
		[66] = {"On Shot",{"Bodyaim when enemy is shooting.",},},
		[67] = {"No Head Safepoint",{"Bodyaim when head hitboxes do not overlap.",},},
		[68] = {"Force",{"Always prioritize bodyaim.",},},
		[69] = {"Lethal",{"Bodyaim when shot will be lethal.",},},
		[70] = {"On Shot",{"Bodyaim when enemy is shooting.",},},
		[71] = {"No Head Safepoint",{"Bodyaim when head hitboxes do not overlap.",},},
		[72] = {"Force",{"Always prioritize bodyaim.",},},
		[73] = {"Lethal",{"Bodyaim when shot will be lethal.",},},
		[74] = {"On Shot",{"Bodyaim when enemy is shooting.",},},
		[75] = {"No Head Safepoint",{"Bodyaim when head hitboxes do not overlap.",},},
		[76] = {"Force",{"Always prioritize bodyaim.",},},
		[77] = {"Lethal",{"Bodyaim when shot will be lethal.",},},
		[78] = {"On Shot",{"Bodyaim when enemy is shooting.",},},
		[79] = {"No Head Safepoint",{"Bodyaim when head hitboxes do not overlap.",},},
		[80] = {"Force",{"Always prioritize bodyaim.",},},
		[81] = {"Lethal",{"Bodyaim when shot will be lethal.",},},
		[82] = {"On Shot",{"Bodyaim when enemy is shooting.",},},
		[83] = {"No Head Safepoint",{"Bodyaim when head hitboxes do not overlap.",},},
		[84] = {"Force",{"Always prioritize bodyaim.",},},
		[85] = {"Lethal",{"Bodyaim when shot will be lethal.",},},
		[86] = {"On Shot",{"Bodyaim when enemy is shooting.",},},
		[87] = {"No Head Safepoint",{"Bodyaim when head hitboxes do not overlap.",},},
		[88] = {"Force",{"Always prioritize bodyaim.",},},
		[89] = {"Lethal",{"Bodyaim when shot will be lethal.",},},
		[90] = {"On Shot",{"Bodyaim when enemy is shooting.",},},
		[91] = {"No Head Safepoint",{"Bodyaim when head hitboxes do not overlap.",},},
		[92] = {"Force",{"Always prioritize bodyaim.",},},
		[93] = {"Lethal",{"Bodyaim when shot will be lethal.",},},
		[94] = {"On Shot",{"Bodyaim when enemy is shooting.",},},
		[95] = {"No Head Safepoint",{"Bodyaim when head hitboxes do not overlap.",},},
		[96] = {"Force",{"Always prioritize bodyaim.",},},
		[97] = {"Lethal",{"Bodyaim when shot will be lethal.",},},
		[98] = {"On Shot",{"Bodyaim when enemy is shooting.",},},
		[99] = {"No Head Safepoint",{"Bodyaim when head hitboxes do not overlap.",},},
	},
};
return(English);